### ISSUE TITLE
King County Schedules are not correct

### ISSUE THREAD

**Issue by Listatta** [OneBusAway/onebusaway#12]
Some king county schedules are not correct, such as Rout 99, it now has service 7 days a week and runs all day but your info still shows as only running morning and evening. Not sure where you need to change your data pull from but your king county info needs updating!!

**Comment by barbeau** [comment]
@Listatta Thanks for the feedback!  The best place to send this information is Open_Transit_Data@soundtransit.org.  Sound Transit maintains the OneBusAway server for Puget Sound, and can work with KCM to ensure the schedules are updated.
