### ISSUE TITLE
Broken links in Wiki\GTFS Realtime Resources\Tutorials

### ISSUE THREAD

**Issue by shahar-zuberi-via** [OneBusAway/onebusaway#15]
Some of the links in the Wiki\GTFS Realtime Resources\Tutorials are broken

**Comment by barbeau** [comment]
Thanks for pointing this out!

We're working on re-posting some of Brian's tutorials.

In the mean-time, you can find links to the archived content here:
https://web.archive.org/web/20190319025904/https://plus.google.com/116552831948529744090/posts/SPn9e6pEbdf
https://web.archive.org/web/20190319025904/https://plus.google.com/116552831948529744090/posts/9TuSp1GWQn8
https://web.archive.org/web/20190319025905/https://plus.google.com/116552831948529744090/posts/YCrsE9gKcUG
https://web.archive.org/web/20190319025906/https://plus.google.com/116552831948529744090/posts/DXu4VmFAtG2
https://web.archive.org/web/20190319025907/https://plus.google.com/116552831948529744090/posts/XCS5F2D2PYM

**Comment by kellytdunn** [comment]
@barbeau I see this is still open; is this something you need help with? I'm looking for beginner-friendly ways to contribute.

**Comment by barbeau** [comment]
@kellytdunn I think that would be great, thanks for the offer! Simple re-posting and re-formatting the above tutorials as part of the wiki on this repository would be great, I think.

FYI, there are plans to move this eventually to the MobilityData GTFS (and GTFS-RT) Resource Center (https://gtfs.mobilitydata.org/) as general GTFS resources. However, that's more of a long-term roadmap item and won't happen in the near future. I gave MobilityData a heads up that you'd like to start work on this, so they will be sure to sync with what you've updated when that move happens.

**Comment by kellytdunn** [comment]
@barbeau great, I can work on this. Are you suggesting I update the links with the archive links listed above or do you know of somewhere else this has been posted fresh? I reached out to Brian but he doesn't seem to have been active in the last few years so I'm not sure if I'll hear back.

**Comment by barbeau** [comment]
I'd suggest re-posting the content as new wiki pages here, and then link to the new wikis instead of the broken links. I reached out to Brian a while back and he approved this. Please be sure to credit him as the original author.

**Comment by kellytdunn** [comment]
Great, I believe it is done. Please take a look and let me know if that looks ok. 
https://github.com/OneBusAway/onebusaway/wiki/GTFS-Realtime-Resources

**Comment by barbeau** [comment]
Thanks @kellytdunn for working in this! They mostly look good, although the first 3 tutorials seem to reference a "below project" in the text that isn't linked to below? I think it's just the link in the last part of the archived stories.

**Comment by kellytdunn** [comment]
Thanks for catching that @barbeau . I have made the corrections.

**Comment by barbeau** [comment]
Thanks @kellytdunn, looks good to me! We appreciate the help. I'll close this issue then as it looks resolved.
