### ISSUE TITLE
broken link to Open Code Of Conduct on Developer Guide wiki

### ISSUE THREAD

**Issue by wkulesza** [OneBusAway/onebusaway#16]
The link to Open Code of Conduct on this wiki page: https://github.com/OneBusAway/onebusaway/wiki/Developer-Guide is broken.
Link to http://todogroup.org/opencodeofconduct/#OneBusAway/conduct@onebusaway.org leads to Page Not Found

**Comment by barbeau** [comment]
As mentioned here on Slack:
https://onebusaway.slack.com/archives/C0FM22XEG/p1587557276021800

...this is also shown in the Slack sign up process:
![image](https://user-images.githubusercontent.com/928045/80034132-eb521f80-84bb-11ea-9878-ea06da0f0fdf.png)

And linked on the Android and iOS repos too, IIRC.

**Comment by barbeau** [comment]
I've used GitHub's template to create a new Code of Conduct we can point to here:
https://github.com/OneBusAway/onebusaway/blob/master/CODE_OF_CONDUCT.md

I'll work on updating the other links.

**Comment by barbeau** [comment]
Ok, I've updated the Dev Guide wiki, OBA Android repo, and Slack links. And I've opened a PR for iOS here - https://github.com/OneBusAway/onebusaway-iphone/pull/1478.

So we should be set! Thanks @wkulesza for opening this!

If anyone finds any other occurrences of the old broken link, please comment and I'll fix them.
