### ISSUE TITLE
myBalsamiq for UI/UX prototyping?

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway#6]
Anyone think it would be beneficial to get [myBalsamiq](http://balsamiq.com/products/mockups/mybalsamiq/) for project UI/UX prototyping? If so it is [available for free](http://support.balsamiq.com/customer/portal/articles/105924#oss):

> # Getting myBalsamiq free for open source projects #

> We're big fans of open source software, and want to support serious open source efforts as much as we can.

> Because myBalsamiq has fixed costs for us month after month, we have to be a little more restrictive in who we give open-source access than we do with Mockups 3 for Desktop (see above).

> To apply for a free myBalsamiq site, your open source project must fulfill the following requirements:

> The project is alive and well and you can prove it (for instance an ohloh.net page, a license approved by the Open Source Initiative, or some press mentions).
> * Your open source project has a publicly accessible website.
> * The project source code is available for download.
> If you are a core committer to an open source project and interested in this program, **please follow these steps to apply**:

> 1. [Sign up for myBalsamiq](http://balsamiq.com/buy?p=myb) and confirm your email address (this is important).
> 1. Email free@balsamiq.com. Be sure to include the following information.We will email you back if we need any clarification.
>    * Your myBalsamiq subdomain:
>    * Your Name and title:
>    * Project Name:
>    * Project Home Page:
>    * Proof that your project is alive and well:
>    * Where we can download your source code:
> 1. That's it! If we approve your application, you'll see that your myBalsamiq site is free the next time you use it. Give us a few days.

/cc @barbeau @aaronbrethorst

**Comment by barbeau** [comment]
Free tools are always nice.  Do they have templates for mobile mockups?  I skimmed through the intro video quick and I saw an "iPhone" tab in a project, but they didn't mention it.

cc @jrharshath, since we were just talking about UI mockups yesterday

**Comment by bbodenmiller** [comment]
Says it is the online version of their [desktop application](http://balsamiq.com/products/mockups/) which definitely has iOS & Android templates. Individuals helping with OBA can also get the [desktop app free as do-gooders](http://support.balsamiq.com/customer/portal/articles/105924-can-i-get-mockups-for-free-#qualify).

**Comment by jrharshath** [comment]
I've been using their desktop version, and their online version is essentially an exact clone of their desktop version (I think its a flex application that runs in the browser as well).

I definitely think it would add value to our community. Sean and I were talking yesterday about the need to lay out a plan/vision for OBA's mobile design, and the need to ensure some harmony between the OBA on android and ios. MyBalsamiq could become a repository of shared design artifacts that all members of the community could view and contribute to, much like github is the repository of our source code.

And while we're on the subject, [MockupsToGo](https://mockupstogo.mybalsamiq.com/projects) has a free repository of many ready-made components that designers can simply import into their own balsamiq (or mybalsamiq) projects.

**Comment by barbeau** [comment]
Sounds good - I'll submit a request to myBalsamiq on behalf of OBA.

**Comment by bbodenmiller** [comment]
Awesome thanks!

**Comment by barbeau** [comment]
Ok, http://onebusaway.mybalsamiq.com/ now exists, and I've requested
conversion to a free open source account.

Looks like next step is to add team members, and I'll need email addresses
for that.  So if you want to be added please email me!

**Comment by barbeau** [comment]
Additional discussion here on the OBA Dev Group:
https://groups.google.com/forum/#!topic/onebusaway-developers/sGb7cyw1bCc
