### ISSUE TITLE
Bump Java source version to 1.8

### ISSUE THREAD

**Issue by kurtraschke** [OneBusAway/onebusaway#8]
Java 7 is EOL, and Java 8 provides useful new features (particularly lambdas).

**Comment by bdferris** [comment]
Man... it feels like only yesterday that I bumped to 7 ;)

**Comment by kurtraschke** [comment]
It's 2018 - is there any objection to this?

@sheldonabrown @sdjacobs @barbeau

**Comment by barbeau** [comment]
Not as far as I know - we should actually have an issue open for Java 9 :)

**Comment by sheldonabrown** [comment]
No objections here.

**Comment by kurtraschke** [comment]
Looks like this was done in 94c041d1669ba6cbfd4e8443990456efa24f8d83.
